Repository RDjarbeng/countdown, pull requests merged in 2022-05, with the labels that each got.

#93 Form enhance
  css/form.css
  css/themes.css
  js/displayCountdowns.js
  js/form.js
  js/formupdate.js
  sw.js
Labels: ui / ux

#95 Updatefallback page
  html/fallback.html
  sw.js
Labels: ui / ux

#99 Add custom sort
  css/countdown-list.css
  html/countdown-list.html
  js/displayCountdowns.js
Labels: enhancement

#102 Updatelistpage
  app.js
  js/displayCountdowns.js
  js/formupdate.js
  sw.js
Labels: enhancement

#103 Readme update
  docs/dev-process.md
  readme.md
Labels: documentation

#105 Fix update list
  app.js
  js/displayCountdowns.js
  sw.js
Labels: bug fix

#106 Repeat every year
  app.js
  css/form.css
  css/themes.css
  js/displayCountdowns.js
  js/form.js
  js/formupdate.js
  js/loadCustomUI.js
  sw.js
Labels: enhancement

#109 Fix missing quotes in Css Imports
  html/about.html
  html/countdown-list.html
  html/fallback.html
  index.html
  sw.js
Labels: bug fix

#112 Version update
  app.js
  docs/dev-process.md
  html/about.html
  readme.md
  sw.js
Labels: documentation

#113 fix for sidebar
  app.js
  css/about.css
  css/countdown-list.css
  css/styles.css
  css/today.css
  html/about.html
  html/countdown-list.html
  html/today.html
  index.html
Labels: ui / ux, bug fix
