Repository RDjarbeng/countdown, pull requests merged in 2022-04, with the labels that each got.

#40 v2 beta
  .prettierignore
  .prettierrc
  app.js
  authors.html
  clock.js
  css/authors.css
  css/countdown-list.css
  css/form.css
  css/styles.css
  css/themes.css
  fallback.html
  html/authors.html
  html/countdown-list.html
  html/fallback.html
  html/form-upload.html
  img/bg-light.svg
  img/bg.svg
  img/bg/basketball_on_court.jpg
  img/bg/earth.jpg
  img/bg/goku.jpg
  img/bg/ship_sky_balloons.jpg
  img/bg/wait_impatient.gif
  js/clock.js
  js/displayCountdowns.js
  js/error.js
  js/form.js
  js/formupdate.js
  js/functions.js
  js/loadCustomUI.js
  js/sidebar.js
  styles.css
  sw.js
Labels: enhancement, ui / ux

#85 Sanitize input
  js/form.js
  js/formupdate.js
  sw.js
Labels: bug fix

#87 update for docs PR
  docs/dev-process.md
  readme.md
Labels: documentation

#83 add docs
  docs/dev-process.md
  readme.md
Labels: documentation

#88 about page updates
  css/about.css
  html/about.html
  html/countdown-list.html
  index.html
  js/sidebar.js
  sw.js
Labels: ui / ux
