Repository RDjarbeng/countdown, pull requests merged in 2022-03, with the labels that each got.

#43 Added MIT license
  LICENSE
Labels: documentation

#51 Fix countdown list
  app.js
  countdown-list.html
  displayCountdowns.js
  index.html
Labels: bug

#54 Fix uc browser working now
  app.js
  countdown-list.html
  displayCountdowns.js
  form.js
  functions.js
  index.html
Labels: bug fix

#46 Whatsapp share functionality and minor changes
  app.js
  authors.html
  clock.js
  countdown-list.css
  countdown-list.html
  displayCountdowns.js
  fallback.html
  form.js
  functions.js
  index.html
  sidebar.js
  styles.css
Labels: enhancement, ui / ux

#69 UI improvements
  countdown-list.css
  themes.css
Labels: ui / ux
